version: 2
jobs:
  build:
    working_directory: ~/clifold
    docker:
      - image: circleci/python:3.6.8
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run: echo $USERNAME
      - run: echo $PASSWORD
      - run:
          name: "Preparing Venv..."
          command: |
            python -m pip install --upgrade pip
            sudo pip install setuptools wheel twine
            pip install -r requirements.txt
            pip install -e .
      - run:
          name: "Linting..."
          command: |
            flake8 clifold/* tests/*
      - run:
          name: "Developing locally..."
          command: |
            python3 setup.py develop
      - run:
          name: "Testing..."
          command: |
            mkdir test-results
            pytest tests/test_commands.py tests/test_main.py --junitxml=test-results/junit.xml
      - run:
          name: "Building & Publishing..."
          command: |
            python setup.py install
            python setup.py sdist bdist_wheel
            twine check dist/*
            twine upload dist/*.whl dist/*.tar.gz -u $USERNAME -p $PASSWORD
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1